# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Yusuf Duyar
email: your-email@example.com
description: >- # this means to ignore newlines until "baseurl:"
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: yusuffduyar
github_username: yusufduyar
remote_theme: "mmistakes/so-simple-theme@3.2.0"
skin: "/assets/css/skins/light.css"

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
locale: "tr-TR"
date_format: "%d-%m-%Y"
lang: "tr"
logo: "/images/logo.jpg"
# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

# Footer Links
footer_links:
  - title: Twitter
    url: https://twitter.com/yusuffduyar
    icon: fab fa-twitter-square
  - title: Instagram
    url: https://instagram.com/yusuffduyar
    icon: fab fa-instagram
  - title: GitHub
    url: https://github.com/yusufduyar
    icon: fab fa-github-square
  - title: Feed
    url: atom.xml
    icon: fas fa-rss-square
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

